### ISSUE TITLE
Bad compilation

### ISSUE THREAD

**Issue by squelix** [jakubroztocil/rrule#263]
**Versions**
```
angular        6.1.1
rrule          2.3.6
```

**Bug**
When I serve/build my application I have this bug
```
ERROR in node_modules/rrule/dist/esm/rrule.d.ts(32,25): error TS2307: Cannot find module 'src/weekday'.
node_modules/rrule/dist/esm/rrule.d.ts(33,25): error TS2307: Cannot find module 'src/weekday'.
node_modules/rrule/dist/esm/rrule.d.ts(34,25): error TS2307: Cannot find module 'src/weekday'.
node_modules/rrule/dist/esm/rrule.d.ts(35,25): error TS2307: Cannot find module 'src/weekday'.
node_modules/rrule/dist/esm/rrule.d.ts(36,25): error TS2307: Cannot find module 'src/weekday'.
node_modules/rrule/dist/esm/rrule.d.ts(37,25): error TS2307: Cannot find module 'src/weekday'.
node_modules/rrule/dist/esm/rrule.d.ts(38,25): error TS2307: Cannot find module 'src/weekday'.
```

**Problem (I guess)**
I went to the `rrule.d.ts` file and I saw this int it : 
```
...
static readonly MO: import("src/weekday").default;
static readonly TU: import("src/weekday").default;
static readonly WE: import("src/weekday").default;
static readonly TH: import("src/weekday").default;
static readonly FR: import("src/weekday").default;
static readonly SA: import("src/weekday").default;
static readonly SU: import("src/weekday").default;
...
```

The problem here is that the import refers to the src and it should not.

I must downgrade to the `2.3.4` which seems to works.

**Comment by davidgoli** [comment]
Verified. Looking into why this is happening, probably introduced by #260... @mattlewis92 any thoughts here?

**Comment by davidgoli** [comment]
probably because we changed `"module": "commonjs"` to `"module": "es2015"` in `tsconfig.json` to support tree shaking

**Comment by davidgoli** [comment]
The Typescript compiler should be emitting `import("./weekday").default` instead of `import("src/weekday").default`; looking for an issue in their repo about this.

**Comment by mattlewis92** [comment]
@squelix what version of typescript are you using?

**Comment by squelix** [comment]
Typescript version 2.9.2

**Comment by davidgoli** [comment]
I can repro this with typescript 3.0.1. I have a fix in #264.

**Comment by davidgoli** [comment]
Published fix in 2.4.0.
